-- Estudiante en repitencia
-- Nombre del estudiante, instituto de origen, contacto que valida sus bitácoras, y estado de su colocación

SELECT 
    e.NOMBRE_COMPLETO AS ESTUDIANTE,
    i.NOMBRE AS INSTITUTO,
    ct.NOMBRE AS CONTACTO_VALIDADOR,
    ec.NOMBRE AS ESTADO_COLOCACION
FROM ESTUDIANTE e
JOIN INSTITUTO i ON e.INSTITUTO_ID_INSTITUTO = i.ID_INSTITUTO
JOIN COLOCACION c ON e.CARNET = c.ESTUDIANTE_CARNET
JOIN PLAZA p ON c.PLAZA_ID_PLAZA = p.ID_PLAZA
JOIN CONTACTO ct ON p.CONTACTO_ID_CONTACTO = ct.ID_CONTACTO
JOIN ESTADO_COLOCACION ec ON c.ESTADO_ID_ESTADO = ec.ID_ESTADO
WHERE e.REPITENCIA = 'S';