-- Generado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   en:        2026-08-14 03:27:42 CST
--   sitio:      Oracle Database 11g
--   tipo:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE BITACORA 
    ( 
     ID_BITACORA              NUMBER  NOT NULL , 
     MES                      NUMBER  NOT NULL , 
     CORRELATIVO              NUMBER  NOT NULL , 
     FECHA                    DATE  NOT NULL , 
     HORAS_TRABAJADAS         NUMBER  NOT NULL , 
     ACTIVIDADES              VARCHAR2 (500 CHAR)  NOT NULL , 
     OBSERVACIONES            VARCHAR2 (250 CHAR)  NOT NULL , 
     VALIDADA                 CHAR (1 CHAR)  NOT NULL , 
     COLOCACION_ID_COLOCACION NUMBER  NOT NULL 
    ) 
;

ALTER TABLE BITACORA 
    ADD CONSTRAINT BITACORA_PK PRIMARY KEY ( ID_BITACORA ) ;

CREATE TABLE CATEDRATICO 
    ( 
     ID_CATEDRATICO         NUMBER  NOT NULL , 
     IDENTIFICACION         VARCHAR2 (20 CHAR)  NOT NULL , 
     NOMBRE                 VARCHAR2 (100 CHAR)  NOT NULL , 
     TELEFONO               VARCHAR2 (15 CHAR) , 
     ESPECIALIDAD           VARCHAR2 (50 CHAR)  NOT NULL , 
     INSTITUTO_ID_INSTITUTO NUMBER  NOT NULL 
    ) 
;

ALTER TABLE CATEDRATICO 
    ADD CONSTRAINT CATEDRATICO_PK PRIMARY KEY ( ID_CATEDRATICO ) ;

CREATE TABLE COLOCACION 
    ( 
     ID_COLOCACION              NUMBER  NOT NULL , 
     FECHA_INICIO               DATE  NOT NULL , 
     FECHA_FIN                  DATE  NOT NULL , 
     ESTADO                     VARCHAR2 (15 CHAR)  NOT NULL , 
     ESTUDIANTE_CARNET          NUMBER  NOT NULL , 
     PLAZA_ID_PLAZA             NUMBER  NOT NULL , 
     CATEDRATICO_ID_CATEDRATICO NUMBER  NOT NULL 
    ) 
;

ALTER TABLE COLOCACION 
    ADD CONSTRAINT COLOCACION_PK PRIMARY KEY ( ID_COLOCACION ) ;

CREATE TABLE CONTACTO 
    ( 
     ID_CONTACTO        NUMBER  NOT NULL , 
     NOMBRE             VARCHAR2 (100 CHAR)  NOT NULL , 
     TELEFONO           VARCHAR2 (15 CHAR)  NOT NULL , 
     CORREO             VARCHAR2 (100)  NOT NULL , 
     EMPRESA_ID_EMPRESA NUMBER  NOT NULL 
    ) 
;

ALTER TABLE CONTACTO 
    ADD CONSTRAINT CONTACTO_PK PRIMARY KEY ( ID_CONTACTO ) ;

CREATE TABLE CRITERIO 
    ( 
     ID_CRITERIO     NUMBER  NOT NULL , 
     NOMBRE_CRITERIO VARCHAR2 (50 CHAR)  NOT NULL , 
     DESCRIPCION     VARCHAR2 (200) 
    ) 
;

ALTER TABLE CRITERIO 
    ADD CONSTRAINT CRITERIO_PK PRIMARY KEY ( ID_CRITERIO ) ;

CREATE TABLE DEPARTAMENTO 
    ( 
     ID_DEPARTAMENTO     NUMBER  NOT NULL , 
     NOMBRE_DEPARTAMENTO VARCHAR2 (50 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE DEPARTAMENTO 
    ADD CONSTRAINT DEPARTAMENTO_PK PRIMARY KEY ( ID_DEPARTAMENTO ) ;

CREATE TABLE DETALLE_EVALUACION 
    ( 
     ID_DETALLE_EVAL          NUMBER  NOT NULL , 
     PUNTUACION               FLOAT , 
     EVALUACION_ID_EVALUACION NUMBER  NOT NULL , 
     CRITERIO_ID_CRITERIO     NUMBER  NOT NULL 
    ) 
;

ALTER TABLE DETALLE_EVALUACION 
    ADD CONSTRAINT DETALLE_EVALUACION_PK PRIMARY KEY ( ID_DETALLE_EVAL ) ;

CREATE TABLE EMPRESA 
    ( 
     ID_EMPRESA       NUMBER  NOT NULL , 
     NOMBRE           VARCHAR2 (50)  NOT NULL , 
     SECTOR_ID_SECTOR NUMBER  NOT NULL 
    ) 
;

ALTER TABLE EMPRESA 
    ADD CONSTRAINT EMPRESA_PK PRIMARY KEY ( ID_EMPRESA ) ;

CREATE TABLE ESTUDIANTE 
    ( 
     CARNET                 NUMBER  NOT NULL , 
     NOMBRE_COMPLETO        VARCHAR2 (100 CHAR)  NOT NULL , 
     CARRERA_TECNICA        VARCHAR2 (50 CHAR)  NOT NULL , 
     DIRECCION              VARCHAR2 (150 CHAR)  NOT NULL , 
     TELEFONO               VARCHAR2 (15 CHAR) , 
     FECHA_NACIMIENTO       DATE  NOT NULL , 
     GENERO                 CHAR (1 CHAR)  NOT NULL , 
     REPITENCIA             CHAR (1 CHAR)  NOT NULL , 
     MUNICIPIO_ID_MUNICIPIO NUMBER  NOT NULL 
    ) 
;

ALTER TABLE ESTUDIANTE 
    ADD CONSTRAINT ESTUDIANTE_PK PRIMARY KEY ( CARNET ) ;

CREATE TABLE EVALUACION 
    ( 
     ID_EVALUACION            NUMBER  NOT NULL , 
     TIPO_EVALUACION          VARCHAR2 (15 CHAR)  NOT NULL , 
     FECHA                    DATE  NOT NULL , 
     COLOCACION_ID_COLOCACION NUMBER  NOT NULL 
    ) 
;

ALTER TABLE EVALUACION 
    ADD CONSTRAINT EVALUACION_PK PRIMARY KEY ( ID_EVALUACION ) ;

CREATE TABLE INSTITUTO 
    ( 
     ID_INSTITUTO   NUMBER  NOT NULL , 
     NOMBRE         VARCHAR2 (100 CHAR)  NOT NULL , 
     DIRECCION      VARCHAR2 (150 CHAR) , 
     CODIGO_MINEDUC VARCHAR2 (20 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE INSTITUTO 
    ADD CONSTRAINT INSTITUTO_PK PRIMARY KEY ( ID_INSTITUTO ) ;

CREATE TABLE MUNICIPIO 
    ( 
     ID_MUNICIPIO                 NUMBER  NOT NULL , 
     NOMBRE_MUNICIPIO             VARCHAR2 (50 CHAR)  NOT NULL , 
     DEPARTAMENTO_ID_DEPARTAMENTO NUMBER  NOT NULL 
    ) 
;

ALTER TABLE MUNICIPIO 
    ADD CONSTRAINT MUNICIPIO_PK PRIMARY KEY ( ID_MUNICIPIO ) ;

CREATE TABLE PLAZA 
    ( 
     ID_PLAZA             NUMBER  NOT NULL , 
     ESPECIALIDAD_TECNICA VARCHAR2 (150 CHAR)  NOT NULL , 
     EMPRESA_ID_EMPRESA   NUMBER  NOT NULL , 
     CONTACTO_ID_CONTACTO NUMBER  NOT NULL 
    ) 
;

ALTER TABLE PLAZA 
    ADD CONSTRAINT PLAZA_PK PRIMARY KEY ( ID_PLAZA ) ;

CREATE TABLE SECTOR 
    ( 
     ID_SECTOR     NUMBER  NOT NULL , 
     NOMBRE_SECTOR VARCHAR2 (150 CHAR)  NOT NULL

    ) 
;

ALTER TABLE SECTOR 
    ADD CONSTRAINT SECTOR_PK PRIMARY KEY ( ID_SECTOR ) ;

ALTER TABLE BITACORA 
    ADD CONSTRAINT BITACORA_COLOCACION_FK FOREIGN KEY 
    ( 
     COLOCACION_ID_COLOCACION
    ) 
    REFERENCES COLOCACION 
    ( 
     ID_COLOCACION
    ) 
;

ALTER TABLE CATEDRATICO 
    ADD CONSTRAINT CATEDRATICO_INSTITUTO_FK FOREIGN KEY 
    ( 
     INSTITUTO_ID_INSTITUTO
    ) 
    REFERENCES INSTITUTO 
    ( 
     ID_INSTITUTO
    ) 
;

ALTER TABLE COLOCACION 
    ADD CONSTRAINT COLOCACION_CATEDRATICO_FK FOREIGN KEY 
    ( 
     CATEDRATICO_ID_CATEDRATICO
    ) 
    REFERENCES CATEDRATICO 
    ( 
     ID_CATEDRATICO
    ) 
;

ALTER TABLE COLOCACION 
    ADD CONSTRAINT COLOCACION_ESTUDIANTE_FK FOREIGN KEY 
    ( 
     ESTUDIANTE_CARNET
    ) 
    REFERENCES ESTUDIANTE 
    ( 
     CARNET
    ) 
;

ALTER TABLE COLOCACION 
    ADD CONSTRAINT COLOCACION_PLAZA_FK FOREIGN KEY 
    ( 
     PLAZA_ID_PLAZA
    ) 
    REFERENCES PLAZA 
    ( 
     ID_PLAZA
    ) 
;

ALTER TABLE CONTACTO 
    ADD CONSTRAINT CONTACTO_EMPRESA_FK FOREIGN KEY 
    ( 
     EMPRESA_ID_EMPRESA
    ) 
    REFERENCES EMPRESA 
    ( 
     ID_EMPRESA
    ) 
;

ALTER TABLE DETALLE_EVALUACION 
    ADD CONSTRAINT DETALLE_EVALUACION_CRITERIO_FK FOREIGN KEY 
    ( 
     CRITERIO_ID_CRITERIO
    ) 
    REFERENCES CRITERIO 
    ( 
     ID_CRITERIO
    ) 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE DETALLE_EVALUACION 
    ADD CONSTRAINT DETALLE_EVAL_EVALUACION_FK FOREIGN KEY 
    ( 
     EVALUACION_ID_EVALUACION
    ) 
    REFERENCES EVALUACION 
    ( 
     ID_EVALUACION
    ) 
;

ALTER TABLE EMPRESA 
    ADD CONSTRAINT EMPRESA_SECTOR_FK FOREIGN KEY 
    ( 
     SECTOR_ID_SECTOR
    ) 
    REFERENCES SECTOR 
    ( 
     ID_SECTOR
    ) 
;

ALTER TABLE ESTUDIANTE 
    ADD CONSTRAINT ESTUDIANTE_MUNICIPIO_FK FOREIGN KEY 
    ( 
     MUNICIPIO_ID_MUNICIPIO
    ) 
    REFERENCES MUNICIPIO 
    ( 
     ID_MUNICIPIO
    ) 
;

ALTER TABLE EVALUACION 
    ADD CONSTRAINT EVALUACION_COLOCACION_FK FOREIGN KEY 
    ( 
     COLOCACION_ID_COLOCACION
    ) 
    REFERENCES COLOCACION 
    ( 
     ID_COLOCACION
    ) 
;

ALTER TABLE MUNICIPIO 
    ADD CONSTRAINT MUNICIPIO_DEPARTAMENTO_FK FOREIGN KEY 
    ( 
     DEPARTAMENTO_ID_DEPARTAMENTO
    ) 
    REFERENCES DEPARTAMENTO 
    ( 
     ID_DEPARTAMENTO
    ) 
;

ALTER TABLE PLAZA 
    ADD CONSTRAINT PLAZA_CONTACTO_FK FOREIGN KEY 
    ( 
     CONTACTO_ID_CONTACTO
    ) 
    REFERENCES CONTACTO 
    ( 
     ID_CONTACTO
    ) 
;

ALTER TABLE PLAZA 
    ADD CONSTRAINT PLAZA_EMPRESA_FK FOREIGN KEY 
    ( 
     EMPRESA_ID_EMPRESA
    ) 
    REFERENCES EMPRESA 
    ( 
     ID_EMPRESA
    ) 
;



-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            14
-- CREATE INDEX                             0
-- ALTER TABLE                             28
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
